/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    UvCell: typeof import('@climblee/uv-ui/components/uv-cell/uv-cell.vue')['default']
    UvIcon: typeof import('@climblee/uv-ui/components/uv-icon/uv-icon.vue')['default']
    UvLine: typeof import('@climblee/uv-ui/components/uv-line/uv-line.vue')['default']
  }
}
