/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    MTabbar: typeof import('./src/components/m-tabbar/index.vue')['default']
    Tabbar: typeof import('./src/components/tabbar/index.vue')['default']
  }
}
